/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jode;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
