/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jode;

import jode.UI.Window;
import jode.values.values;

public class App {
    public static void main(String[] args) {
        Window win = new Window();
        win.setTitle(values.title);
        win.setSize(values.width,values.height);

        
        win.isCenter(true);
    }
}
